-- Setup neovim lua configuration
require('zuli.opt')
require('zuli.search')
require('zuli.lsp')
require('zuli.completion')
require('zuli.neovide')
require('zuli.keymap')
require('zuli.nvim-tree')
require('zuli.colors')
require('zuli.debug')
require('zuli.lsp-toggle')
